# for local development
version: "3.7"
services:
  auto-surf:
    image: dscribe/auto-surf
    build:
      context: .
      target: "develop-stage"
    volumes:
      - ".:/app"
    tty: true
    command: yarn
